general:
  data_path: data/
  model_name: digit82/kobart-summarization
  output_dir: ./
inference:
  batch_size: 32
  ckt_dir: model-ckt-path
  early_stopping: true
  generate_max_length: 200
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 200
  encoder_max_len: 512
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#DateOfBirth#'
  - '#PassportNumber#'
  - '#SSN#'
  - '#CardNumber#'
  - '#CarNumber#'
  - '#Email#'
training:
  dataloader_drop_last: false
  dataloader_num_workers: 8
  early_stopping_patience: 1
  early_stopping_threshold: 0.001
  eval_steps: 400
  evaluation_strategy: steps
  fp16: true
  generation_max_length: 200
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  group_by_length: true
  learning_rate: 0.0002731304037760795
  load_best_model_at_end: true
  logging_steps: 100
  num_train_epochs: 5
  output_dir: baseline_test1
  overwrite_output_dir: false
  per_device_eval_batch_size: 48
  per_device_train_batch_size: 16
  predict_with_generate: true
  remove_unused_columns: true
  report_to: all
  save_steps: 400
  save_total_limit: 1
  seed: 42
  torch_empty_cache_steps: 10
  warmup_steps: 100
  weight_decay: 0.017648866162561238
wandb:
  entity: ahyeon1-
  name: base
  project: nlp-5
